--
-- Tabella dei contenuti degli mms
--
CREATE TABLE IF NOT EXISTS mmscontents (
  id INTEGER NOT NULL PRIMARY KEY,
  sol_id INTEGER NOT NULL REFERENCES sols(id) ON DELETE CASCADE ON UPDATE CASCADE,
  pol_id INTEGER NOT NULL REFERENCES pols(id) ON DELETE CASCADE ON UPDATE CASCADE,
  source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE ON UPDATE CASCADE,
  mm_id INTEGER NOT NULL REFERENCES mms(id) ON DELETE CASCADE ON UPDATE CASCADE,
  content_type VARCHAR( 255 ),
  filename VARCHAR( 255 ) DEFAULT 'No name',
  file_path VARCHAR( 255 ),
  file_size INTEGER
);
