--
-- Tabella dei canali della chat palalk
--
CREATE TABLE IF NOT EXISTS paltalk_rooms (
  id INTEGER NOT NULL PRIMARY KEY,
  sol_id INTEGER NOT NULL REFERENCES sols(id) ON DELETE CASCADE ON UPDATE CASCADE,
  pol_id INTEGER NOT NULL REFERENCES pols(id) ON DELETE CASCADE ON UPDATE CASCADE,
  source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE ON UPDATE CASCADE,
  capture_date TIMESTAMP NOT NULL DEFAULT '1990-01-01 00:00:00',
  decoding_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  viewed_date TIMESTAMP NOT NULL DEFAULT '1990-01-01 00:00:00',
  first_visualization_user_id INTEGER,
  flow_info VARCHAR( 255 ) NOT NULL,
  room VARCHAR( 255 ),
  end_date TIMESTAMP NOT NULL DEFAULT '1990-01-01 00:00:00',
  room_path VARCHAR( 255 ),
  duration VARCHAR( 255 ),
  rusers VARCHAR( 255 ),
  rnick VARCHAR( 255 )
);
