--
-- Tabella delle sessioni
--
CREATE TABLE IF NOT EXISTS sols (
  id INTEGER NOT NULL AUTO_INCREMENT,
  pol_id INTEGER NOT NULL,
  name VARCHAR( 255 ) NOT NULL,
  start_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  end_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  decoding_start TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  decoding_end TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  status ENUM('EMPTY', 'START DECODING', 'DECODING', 'DECODING COMPLETED') DEFAULT 'EMPTY',
  rm INTEGER DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (pol_id) REFERENCES pols(id) ON DELETE CASCADE
) TYPE = MYISAM ;
